# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calculator(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(499, 548)
        calculator.setLayoutDirection(QtCore.Qt.RightToLeft)
        calculator.setStyleSheet("background-color:rgb(136, 138, 133)")
        self.centralwidget = QtWidgets.QWidget(calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.inputEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.inputEdit.setGeometry(QtCore.QRect(30, 40, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.inputEdit.setFont(font)
        self.inputEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.inputEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.085 rgba(2, 79, 0, 255), stop:0.19 rgba(50, 147, 22, 255), stop:0.275 rgba(236, 191, 49, 255), stop:0.39 rgba(243, 61, 34, 255), stop:0.555 rgba(135, 81, 60, 255), stop:0.667 rgba(121, 75, 255, 255), stop:0.825 rgba(164, 255, 244, 255), stop:0.885 rgba(104, 222, 71, 255), stop:1 rgba(93, 128, 0, 255));")
        self.inputEdit.setText("")
        self.inputEdit.setObjectName("inputEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 120, 386, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.divButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.divButton.setFont(font)
        self.divButton.setObjectName("divButton")
        self.gridLayout.addWidget(self.divButton, 0, 0, 1, 1)
        self.mulButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mulButton.setFont(font)
        self.mulButton.setObjectName("mulButton")
        self.gridLayout.addWidget(self.mulButton, 0, 1, 1, 1)
        self.minusButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.gridLayout.addWidget(self.minusButton, 0, 2, 1, 1)
        self.plusButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.gridLayout.addWidget(self.plusButton, 0, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 220, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fourButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.horizontalLayout.addWidget(self.fourButton)
        self.treeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeButton.setFont(font)
        self.treeButton.setObjectName("treeButton")
        self.horizontalLayout.addWidget(self.treeButton)
        self.twoButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.horizontalLayout.addWidget(self.twoButton)
        self.oneButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.horizontalLayout.addWidget(self.oneButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(60, 300, 376, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.verticalLayoutWidget_2.setFont(font)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.eightButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.horizontalLayout_2.addWidget(self.eightButton)
        self.sevenButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.horizontalLayout_2.addWidget(self.sevenButton)
        self.sixButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.horizontalLayout_2.addWidget(self.sixButton)
        self.fiveButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.horizontalLayout_2.addWidget(self.fiveButton)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 370, 376, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.verticalLayoutWidget_3.setFont(font)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zeroButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.zeroButton_2.setFont(font)
        self.zeroButton_2.setObjectName("zeroButton_2")
        self.horizontalLayout_3.addWidget(self.zeroButton_2)
        self.zeroButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.horizontalLayout_3.addWidget(self.zeroButton)
        self.nineButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.horizontalLayout_3.addWidget(self.nineButton)
        calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 22))
        self.menubar.setObjectName("menubar")
        calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(calculator)
        self.statusbar.setObjectName("statusbar")
        calculator.setStatusBar(self.statusbar)

        self.retranslateUi(calculator)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "Calculator"))
        self.inputEdit.setToolTip(_translate("calculator", "<html><head/><body><p>Input Here</p><p><br/></p></body></html>"))
        self.inputEdit.setPlaceholderText(_translate("calculator", "Input Here"))
        self.divButton.setText(_translate("calculator", "/"))
        self.mulButton.setText(_translate("calculator", "*"))
        self.minusButton.setText(_translate("calculator", "-"))
        self.plusButton.setText(_translate("calculator", "+"))
        self.fourButton.setText(_translate("calculator", "4"))
        self.treeButton.setText(_translate("calculator", "3"))
        self.twoButton.setText(_translate("calculator", "2"))
        self.oneButton.setText(_translate("calculator", "1"))
        self.eightButton.setText(_translate("calculator", "8"))
        self.sevenButton.setText(_translate("calculator", "7"))
        self.sixButton.setText(_translate("calculator", "6"))
        self.fiveButton.setText(_translate("calculator", "5"))
        self.zeroButton_2.setText(_translate("calculator", "clearButton"))
        self.zeroButton.setText(_translate("calculator", "0"))
        self.nineButton.setText(_translate("calculator", "9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calculator = QtWidgets.QMainWindow()
    ui = Ui_calculator()
    ui.setupUi(calculator)
    calculator.show()
    sys.exit(app.exec_())
